/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author lera
 */
public class PrintSetupPanel extends javax.swing.JPanel {

    private boolean halfAct;
    /**
     * Creates new form PrintSetupPanel
     */
    public PrintSetupPanel() {
        initComponents();
        halfAct = chcHalfAct.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radiobtnPrintAll = new javax.swing.JRadioButton();
        radiobtnSelect = new javax.swing.JRadioButton();
        chcHalfAct = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        buttonGroup1.add(radiobtnPrintAll);
        radiobtnPrintAll.setSelected(true);
        radiobtnPrintAll.setText("печатать всё");

        buttonGroup1.add(radiobtnSelect);
        radiobtnSelect.setText("выбрать");

        chcHalfAct.setText("половина акта");
        chcHalfAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcHalfActActionPerformed(evt);
            }
        });

        jCheckBox2.setText("перенос по слогам");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radiobtnPrintAll)
                    .addComponent(radiobtnSelect)
                    .addComponent(chcHalfAct)
                    .addComponent(jCheckBox2))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radiobtnPrintAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radiobtnSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chcHalfAct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chcHalfActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcHalfActActionPerformed
        // TODO add your handling code here:
        halfAct = chcHalfAct.isSelected();// задаём значение флага печати половины акта
    }//GEN-LAST:event_chcHalfActActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chcHalfAct;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtnPrintAll;
    private javax.swing.JRadioButton radiobtnSelect;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the halfAct
     */
    public boolean isHalfAct() {
        return halfAct;
    }
}
